kind: Service
apiVersion: v1
metadata:
  name: backend-rollout-bluegreen-active
  namespace: skills
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: backend-rollout-bluegreen-preview
  namespace: skills
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080