apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-app
  namespace: skills
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: backend-rollout-bluegreen-active
      previewService: backend-rollout-bluegreen-preview
      autoPromotionEnabled: true