kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: skills
spec:
  selector:
    app: backend
    version: {{ .Values.version }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080