apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: skills
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: backend
        version: {{ .Values.version }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "{{ .Values.preStopSleep }}"]
