apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-app
  namespace: skills
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: frontend
        version: {{ .Values.version }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "{{ .Values.preStopSleep }}"]