kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: skills
spec:
  selector:
    app: frontend
    version: {{ .Values.version }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80