kind: Service
apiVersion: v1
metadata:
  name: frontend-rollout-bluegreen-active
  namespace: skills
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-rollout-bluegreen-preview
  namespace: skills
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80